In [40]:
import pandas as pd

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import f1_score

from sklearn.model_selection import train_test_split

In [2]:
titanic = pd.read_csv('titanic.csv')

In [4]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [6]:
titanic.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [15]:
titanic.groupby(['Pclass','Sex'])['Age'].mean()

Pclass  Sex   
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: Age, dtype: float64

In [14]:
titanic[titanic.Age.isna()].groupby('Pclass')['PassengerId'].count()

Pclass
1     30
2     11
3    136
Name: PassengerId, dtype: int64

In [17]:
titanic.loc[titanic.Age.isna(),'Age'] = titanic['Age'].mean()


In [18]:
titanic.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [19]:
titanic = titanic[['Survived', 'Pclass', 'Sex', 'Age', 'Fare']]

### Закодируем пол в число

In [27]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
# >>> le.fit([1, 2, 2, 6])
# LabelEncoder()
# >>> le.classes_
# array([1, 2, 6])
# >>> le.transform([1, 1, 2, 6])
# array([0, 0, 1, 2]...)
# >>> le.inverse_transform([0, 0, 1, 2])
# array([1, 1, 2, 6])

In [30]:
titanic['POL'] = le.fit_transform(titanic['Sex'])

<ipython-input-30-91a0b98eeb11>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic['POL'] = le.fit_transform(titanic['Sex'])


In [31]:
titanic

Survived  Pclass     Sex        Age     Fare  POL
0           0       3    male  22.000000   7.2500    1
1           1       1  female  38.000000  71.2833    0
2           1       3  female  26.000000   7.9250    0
3           1       1  female  35.000000  53.1000    0
4           0       3    male  35.000000   8.0500    1
..        ...     ...     ...        ...      ...  ...
886         0       2    male  27.000000  13.0000    1
887         1       1  female  19.000000  30.0000    0
888         0       3  female  29.699118  23.4500    0
889         1       1    male  26.000000  30.0000    1
890         0       3    male  32.000000   7.7500    1

[891 rows x 6 columns]

In [32]:
X_train, X_test, y_train, y_test= train_test_split(titanic.drop(['Survived','Sex'],axis=1), 
                                                  titanic['Survived'],
                                                  test_size = 0.2,
                                                  random_state = 2121212)

In [33]:
print(X_train.shape,X_test.shape)

(712, 4) (179, 4)


In [34]:
clf = DecisionTreeClassifier()

In [35]:
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [36]:
pred = clf.predict(X_test)

In [37]:
pred

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0])

In [39]:
frame = {'Важность параметра':clf.feature_importances_, 'Фича':X_train.columns}
result = pd.DataFrame(frame)
result.sort_values(by='Важность параметра', ascending=False)

Важность параметра    Фича
2            0.327282    Fare
3            0.296356     POL
1            0.245610     Age
0            0.130753  Pclass

In [41]:
print('F1 score', f1_score(y_test,pred))

F1 score 0.7499999999999999
